# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "nvme" "xhci_pci" "usbhid" "usb_storage" "uas" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.swraid = {
    enable = true;

    mdadmConf = ''
      MAILADDR root
    '';
  };

  environment.systemPackages = with pkgs; [
    mdadm
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1ead3e1f-ebdd-4bac-b0ef-655bd8862e85";
      fsType = "ext4";
    };

  fileSystems."/work" =
    { device = "/dev/disk/by-uuid/b3b39d14-a3a7-4b7d-8fec-2c4709bee98e";
      fsType = "ext4";
    };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/520b4555-0454-4cc3-9d38-94726805fb93";
    fsType = "ext4";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4fb52980-71a7-43af-a556-855b0ebb2f54"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
