---
- hosts: ubuntu_servers
  become: 'true'
  tasks:
  - name: 'Upgrade Ubuntu packages'
    apt:
      upgrade: 'yes'
      update_cache: yes
      cache_valid_time: 86400
- hosts: rhel_servers
  become: 'true'
  tasks:
  - name: 'Upgrade RHEL Packages'
    yum:
      name: "*"
      state: latest
      update_cache: true
